version: 2.1
commands: 
  destroy_environment: 
    steps: 
      - 
        run: 
          command: "aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}\n"
          name: "Destroy environment"
          when: on_fail
jobs: 
  configure_infrastructure: 
    docker: 
      - 
        image: "python:3.7-alpine3.11"
    steps: 
      - checkout
      - 
        add_ssh_keys: 
          fingerprints: 
            - "6e:e2:4f:35:8e:c5:c9:98:09:a1:8a:83:8c:53:fa:98"
      - 
        run: 
          command: |
              # Install Ansible
              apk add --update ansible
          name: "Install Ansible"
      - 
        run: 
          command: "# Your command  \n\
              ansible-playbook -i inventory main4.yml  \n"
          name: "Run Playbook and Configure server"
  create_infrastructure: 
    docker: 
      - 
        image: amazon/aws-cli
    steps: 
      - checkout
      - 
        run: 
          command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
                --region us-west-2
          name: "Create Cloudformation Stack"
  say-hello: 
    docker: 
      - 
        image: "cimg/base:stable"
    steps: 
      - checkout
      - 
        run: 
          command: "echo Hello, World!"
          name: "Say hello"
  smoke_test: 
    docker: 
      - 
        image: "alpine:latest"
    steps: 
      - checkout
      - 
        run: "apk add --update curl"
      - 
        run: 
          command: "return 1"
          name: "smoke test"
      - destroy_environment
workflows: 
  say-hello-workflow: 
    jobs: 
      - create_infrastructure
      - 
        smoke_test: 
          requires: 
            - create_infrastructure

